[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]

# [language-server.basedpyright]
# command = "basedpyright-langserver"
# args = ["--stdio"]
# except-features = ["format", "code-action"]

# [language-server.pylsp.config.pylsp]
# plugins.ruff.enabled = true
# plugins.black.enabled = true

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
typeCheckingMode = "basic"
diagnosticMode = "openFilesOnly"
diagnosticSeverityOverrides = { reportExplicitAny = "none" }

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

